---
- name: PostgreSQL cluster preflight
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Include preflight tasks
      ansible.builtin.import_tasks: tasks/01_preflight.yml

- name: PostgreSQL cluster base configuration
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Include base configuration tasks
      ansible.builtin.import_tasks: tasks/02_base_config.yml

- name: PostgreSQL primary configuration
  hosts: pgsql_primary
  gather_facts: false
  become: true
  tasks:
    - name: Include primary configuration tasks
      ansible.builtin.import_tasks: tasks/03_primary.yml

- name: PostgreSQL standby configuration
  hosts: pgsql_standby
  gather_facts: false
  become: true
  tasks:
    - name: Include standby configuration tasks
      ansible.builtin.import_tasks: tasks/04_standby.yml

- name: PostgreSQL cluster bootstrap
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Include cluster bootstrap tasks
      ansible.builtin.import_tasks: tasks/05_cluster_bootstrap.yml

- name: PostgreSQL cluster final verification
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Include verification tasks
      ansible.builtin.import_tasks: tasks/06_verify_cluster.yml

- name: PostgreSQL application database initialization
  hosts: pgsql_primary
  gather_facts: false
  become: true
  tasks:
    - name: Include app database initialization tasks
      ansible.builtin.import_tasks: tasks/07_init_app_db.yml
