---
assume_prepared: false

# max_connections applied on every node; 0 keeps the engine default.
mysql_max_connections: 0

mysql_gr_autorejoin_tries: 10
mysql_gr_member_expel_timeout: 5
mysql_gr_unreachable_majority_timeout: 60
mysql_gr_exit_state_action: READ_ONLY

mysql_start_timeout_seconds: 300
mysqlsh_reset_gr_timeout_seconds: 180
mysqlsh_configure_timeout_seconds: 600
mysqlsh_normalize_timeout_seconds: 180
